import { Employee, Task } from './types';

export const mockEmployees: Employee[] = [
  {
    id: 'E001',
    name: 'Priya Shah',
    role: 'Senior Full Stack Developer',
    department: 'Engineering',
    location: 'Toronto',
    timezone: 'America/Toronto',
    availability: 60,
    availabilityStatus: 'Partial',
    readiness: 'Ready',
    yearsExp: 8,
    avatar: 'https://picsum.photos/seed/priya/200/200',
    skills: [
      { name: 'React', rating: 8 },
      { name: 'Node.js', rating: 7 },
      { name: 'Azure', rating: 8 },
      { name: 'Terraform', rating: 4 },
      { name: 'Stakeholder Communication', rating: 8 },
    ],
    certifications: ['Azure Developer Associate'],
    pastProjects: ['Client Portal Modernization', 'Claims Dashboard'],
    interests: ['Cloud architecture', 'Mentoring'],
    careerGoals: 'Grow into technical lead role',
    resume: {
      fileName: 'Priya_Shah_Resume.pdf',
      updatedAt: '2026-06-10T14:30:00.000Z',
      note: 'Added recent Azure portal modernization work.',
    },
    projectInterests: ['T001'],
  },
  {
    id: 'E002',
    name: 'Jordan Lee',
    role: 'Cloud Security Analyst',
    department: 'Security',
    location: 'Montreal',
    timezone: 'America/Toronto',
    availability: 15,
    availabilityStatus: 'Busy',
    readiness: 'Busy',
    yearsExp: 6,
    avatar: 'https://picsum.photos/seed/jordan/200/200',
    skills: [
      { name: 'Cloud Security', rating: 9 },
      { name: 'Azure', rating: 8 },
      { name: 'Risk Assessment', rating: 8 },
      { name: 'Python', rating: 5 },
      { name: 'Compliance', rating: 7 },
    ],
    certifications: ['Security+', 'Azure Security Engineer'],
    pastProjects: ['Zero Trust Rollout', 'IAM Review'],
    interests: ['Security automation'],
    careerGoals: 'Move into security architecture',
  },
  {
    id: 'E003',
    name: 'Maya Chen',
    role: 'Data Analyst',
    department: 'Analytics',
    location: 'Vancouver',
    timezone: 'America/Vancouver',
    availability: 85,
    availabilityStatus: 'Available',
    readiness: 'Ready',
    yearsExp: 4,
    avatar: 'https://picsum.photos/seed/maya/200/200',
    skills: [
      { name: 'SQL', rating: 8 },
      { name: 'Power BI', rating: 7 },
      { name: 'Python', rating: 6 },
      { name: 'Data Modeling', rating: 6 },
      { name: 'Excel', rating: 9 },
    ],
    certifications: ['PL-300 Power BI Data Analyst'],
    pastProjects: ['Revenue Forecasting', 'Operations Metrics'],
    interests: ['Data storytelling', 'Forecasting'],
    careerGoals: 'Become analytics lead',
  },
  {
    id: 'E004',
    name: 'Ethan Brooks',
    role: 'Project Manager',
    department: 'Delivery',
    location: 'Ottawa',
    timezone: 'America/Toronto',
    availability: 50,
    availabilityStatus: 'Partial',
    readiness: 'Ready',
    yearsExp: 10,
    avatar: 'https://picsum.photos/seed/ethan/200/200',
    skills: [
      { name: 'Agile Delivery', rating: 9 },
      { name: 'Stakeholder Management', rating: 9 },
      { name: 'Budgeting', rating: 7 },
      { name: 'Risk Management', rating: 8 },
      { name: 'Healthcare Domain', rating: 6 },
    ],
    certifications: ['PMP', 'CSM'],
    pastProjects: ['Healthcare Portal', 'ERP Upgrade'],
    interests: ['Delivery excellence'],
    careerGoals: 'Lead larger transformation programs',
  },
  {
    id: 'E005',
    name: 'Sofia Martinez',
    role: 'UX Designer',
    department: 'Design',
    location: 'Calgary',
    timezone: 'America/Edmonton',
    availability: 75,
    availabilityStatus: 'Available',
    readiness: 'Ready',
    yearsExp: 5,
    avatar: 'https://picsum.photos/seed/sofia/200/200',
    skills: [
      { name: 'UX Research', rating: 8 },
      { name: 'Figma', rating: 9 },
      { name: 'Design Systems', rating: 7 },
      { name: 'Accessibility', rating: 7 },
      { name: 'Service Design', rating: 6 },
    ],
    certifications: ['Google UX Design Certificate'],
    pastProjects: ['Mobile Banking Redesign', 'Employee Portal'],
    interests: ['Accessibility', 'Design systems'],
    careerGoals: 'Move into product design leadership',
  },
  {
    id: 'E006',
    name: 'Noah Patel',
    role: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Toronto',
    timezone: 'America/Toronto',
    availability: 70,
    availabilityStatus: 'Available',
    readiness: 'Ready',
    yearsExp: 7,
    avatar: 'https://picsum.photos/seed/noah/200/200',
    skills: [
      { name: 'Terraform', rating: 8 },
      { name: 'Azure', rating: 7 },
      { name: 'Azure DevOps', rating: 8 },
      { name: 'Kubernetes', rating: 7 },
      { name: 'CI/CD', rating: 9 },
      { name: 'Monitoring', rating: 6 },
    ],
    certifications: ['CKA', 'Azure Administrator'],
    pastProjects: ['Cloud Migration', 'CI Pipeline Upgrade'],
    interests: ['Platform engineering'],
    careerGoals: 'Become cloud platform architect',
  },
  {
    id: 'E007',
    name: 'Ava Wilson',
    role: 'Business Analyst',
    department: 'Consulting',
    location: 'Halifax',
    timezone: 'America/Halifax',
    availability: 45,
    availabilityStatus: 'Partial',
    readiness: 'Ready',
    yearsExp: 5,
    avatar: 'https://picsum.photos/seed/ava/200/200',
    skills: [
      { name: 'Requirements Gathering', rating: 9 },
      { name: 'Process Mapping', rating: 8 },
      { name: 'SQL', rating: 5 },
      { name: 'Stakeholder Communication', rating: 8 },
      { name: 'Insurance Domain', rating: 7 },
    ],
    certifications: ['CBAP'],
    pastProjects: ['Claims Intake Redesign', 'Policy Admin Discovery'],
    interests: ['Business process improvement'],
    careerGoals: 'Grow into product owner role',
  },
  {
    id: 'E008',
    name: 'Liam Nguyen',
    role: 'Backend Developer',
    department: 'Engineering',
    location: 'Remote',
    timezone: 'America/Toronto',
    availability: 20,
    availabilityStatus: 'Busy',
    readiness: 'Busy',
    yearsExp: 3,
    avatar: 'https://picsum.photos/seed/liam/200/200',
    skills: [
      { name: 'Java', rating: 7 },
      { name: 'Spring Boot', rating: 7 },
      { name: 'SQL', rating: 6 },
      { name: 'API Design', rating: 6 },
      { name: 'Cloud Security', rating: 3 },
    ],
    certifications: ['Oracle Java Associate'],
    pastProjects: ['Payments API', 'Internal Tools'],
    interests: ['Distributed systems'],
    careerGoals: 'Become senior backend engineer',
  },
  {
    id: 'E009',
    name: 'Amira Khan',
    role: 'Change Management Lead',
    department: 'Delivery',
    location: 'Toronto',
    timezone: 'America/Toronto',
    availability: 65,
    availabilityStatus: 'Available',
    readiness: 'Ready',
    yearsExp: 9,
    avatar: 'https://picsum.photos/seed/amira/200/200',
    skills: [
      { name: 'Change Management', rating: 9 },
      { name: 'Training', rating: 8 },
      { name: 'Stakeholder Communication', rating: 7 },
      { name: 'Agile Delivery', rating: 6 },
      { name: 'Healthcare Domain', rating: 5 },
    ],
    certifications: ['Prosci Change Practitioner'],
    pastProjects: ['ERP Adoption', 'Healthcare Training Rollout'],
    interests: ['Manager enablement', 'Adoption metrics'],
    careerGoals: 'Lead complex transformation adoption programs',
  },
  {
    id: 'E010',
    name: 'Marcus Reed',
    role: 'Legacy Systems Specialist',
    department: 'Engineering',
    location: 'Ottawa',
    timezone: 'America/Toronto',
    availability: 35,
    availabilityStatus: 'Partial',
    readiness: 'Ready',
    yearsExp: 12,
    avatar: 'https://picsum.photos/seed/marcus/200/200',
    skills: [
      { name: 'Mainframe COBOL', rating: 6 },
      { name: 'API Design', rating: 7 },
      { name: 'Java', rating: 6 },
      { name: 'SQL', rating: 7 },
      { name: 'Documentation', rating: 8 },
    ],
    certifications: ['AWS Cloud Practitioner'],
    pastProjects: ['Claims Mainframe Assessment', 'Legacy API Wrapper'],
    interests: ['Legacy modernization', 'Knowledge transfer'],
    careerGoals: 'Modernize legacy platforms with cloud-native teams',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'T001',
    name: 'Project Phoenix Client Portal',
    type: 'Client Project',
    description: 'Modernize a client-facing portal with secure login, dashboards, and cloud deployment.',
    urgency: 'High',
    deadline: '2026-06-28',
    estHours: 160,
    requiredSkills: ['React', 'Azure', 'Stakeholder Communication', 'Terraform'],
    optionalSkills: ['UX Research', 'Accessibility'],
    requiredSkillSpecs: [
      { name: 'React', minRating: 7, importance: 'high' },
      { name: 'Azure', minRating: 7, importance: 'high' },
      { name: 'Stakeholder Communication', minRating: 6, importance: 'medium' },
      { name: 'Terraform', minRating: 5, importance: 'medium' },
    ],
    optionalSkillSpecs: [
      { name: 'UX Research', minRating: 5 },
      { name: 'Accessibility', minRating: 5 },
    ],
    location: 'Toronto',
    remote: true,
    teamSize: 3,
    seniority: 'Senior',
    staffingMode: 'Team',
    status: 'Ready to Staff',
  },
  {
    id: 'T002',
    name: 'Cloud Security Gap Review',
    type: 'Internal Work',
    description: 'Review current Azure environments and identify security risks, compliance gaps, and remediation steps.',
    urgency: 'High',
    deadline: '2026-06-21',
    estHours: 80,
    requiredSkills: ['Cloud Security', 'Azure', 'Risk Assessment', 'Compliance'],
    optionalSkills: ['Python'],
    requiredSkillSpecs: [
      { name: 'Cloud Security', minRating: 8, importance: 'high' },
      { name: 'Azure', minRating: 7, importance: 'high' },
      { name: 'Risk Assessment', minRating: 7, importance: 'high' },
      { name: 'Compliance', minRating: 6, importance: 'medium' },
    ],
    optionalSkillSpecs: [{ name: 'Python', minRating: 4 }],
    location: 'Remote',
    remote: true,
    teamSize: 1,
    seniority: 'Mid-Senior',
    staffingMode: 'One Employee',
    status: 'At Risk',
  },
  {
    id: 'T003',
    name: 'Operations Reporting Dashboard',
    type: 'Internal Work',
    description: 'Build a Power BI dashboard for operations leaders using SQL data sources and executive KPIs.',
    urgency: 'Medium',
    deadline: '2026-07-05',
    estHours: 90,
    requiredSkills: ['Power BI', 'SQL', 'Data Modeling', 'Stakeholder Communication'],
    optionalSkills: ['Python'],
    requiredSkillSpecs: [
      { name: 'Power BI', minRating: 7, importance: 'high' },
      { name: 'SQL', minRating: 7, importance: 'high' },
      { name: 'Data Modeling', minRating: 6, importance: 'medium' },
      { name: 'Stakeholder Communication', minRating: 5, importance: 'medium' },
    ],
    optionalSkillSpecs: [{ name: 'Python', minRating: 5 }],
    location: 'Vancouver',
    remote: true,
    teamSize: 1,
    seniority: 'Intermediate',
    staffingMode: 'One Employee',
    status: 'New',
  },
  {
    id: 'T004',
    name: 'Healthcare Workflow Discovery',
    type: 'Client Project',
    description: 'Run discovery sessions, map current workflows, document requirements, and prepare implementation recommendations.',
    urgency: 'Medium',
    deadline: '2026-06-30',
    estHours: 120,
    requiredSkills: ['Requirements Gathering', 'Process Mapping', 'Healthcare Domain', 'Stakeholder Management'],
    optionalSkills: ['Agile Delivery'],
    requiredSkillSpecs: [
      { name: 'Requirements Gathering', minRating: 8, importance: 'high' },
      { name: 'Process Mapping', minRating: 7, importance: 'high' },
      { name: 'Healthcare Domain', minRating: 5, importance: 'medium' },
      { name: 'Stakeholder Management', minRating: 7, importance: 'medium' },
    ],
    optionalSkillSpecs: [{ name: 'Agile Delivery', minRating: 5 }],
    location: 'Ottawa',
    remote: true,
    teamSize: 2,
    seniority: 'Senior',
    staffingMode: 'Team',
    status: 'Needs Review',
  },
  {
    id: 'T005',
    name: 'Design System Accessibility Pass',
    type: 'Internal Work',
    description: 'Audit the current design system for accessibility issues and propose reusable component updates.',
    urgency: 'Low',
    deadline: '2026-07-12',
    estHours: 60,
    requiredSkills: ['Figma', 'Accessibility', 'Design Systems', 'UX Research'],
    optionalSkills: ['Service Design'],
    requiredSkillSpecs: [
      { name: 'Figma', minRating: 8, importance: 'high' },
      { name: 'Accessibility', minRating: 7, importance: 'high' },
      { name: 'Design Systems', minRating: 7, importance: 'medium' },
      { name: 'UX Research', minRating: 5, importance: 'medium' },
    ],
    optionalSkillSpecs: [{ name: 'Service Design', minRating: 4 }],
    location: 'Remote',
    remote: true,
    teamSize: 1,
    seniority: 'Intermediate',
    staffingMode: 'One Employee',
    status: 'Ready to Staff',
  },
  {
    id: 'T006',
    name: 'Cloud Migration Pipeline Setup',
    type: 'Client Project',
    description: 'Create reusable CI/CD pipelines and infrastructure templates for a cloud migration project.',
    urgency: 'High',
    deadline: '2026-06-25',
    estHours: 140,
    requiredSkills: ['Terraform', 'Azure DevOps', 'CI/CD', 'Kubernetes'],
    optionalSkills: ['Monitoring', 'Cloud Security'],
    requiredSkillSpecs: [
      { name: 'Terraform', minRating: 8, importance: 'high' },
      { name: 'Azure DevOps', minRating: 8, importance: 'high' },
      { name: 'CI/CD', minRating: 8, importance: 'high' },
      { name: 'Kubernetes', minRating: 6, importance: 'medium' },
    ],
    optionalSkillSpecs: [
      { name: 'Monitoring', minRating: 5 },
      { name: 'Cloud Security', minRating: 5 },
    ],
    location: 'Toronto',
    remote: true,
    teamSize: 2,
    seniority: 'Senior',
    staffingMode: 'Team',
    status: 'At Risk',
  },
  {
    id: 'T007',
    name: 'Legacy Claims API Bridge',
    type: 'Client Project',
    description: 'Wrap claims mainframe functions with documented APIs so the digital claims team can modernize safely.',
    urgency: 'High',
    deadline: '2026-06-24',
    estHours: 110,
    requiredSkills: ['Mainframe COBOL', 'API Design', 'Java', 'SQL'],
    optionalSkills: ['Documentation', 'Spring Boot'],
    requiredSkillSpecs: [
      { name: 'Mainframe COBOL', minRating: 7, importance: 'critical' },
      { name: 'API Design', minRating: 6, importance: 'high' },
      { name: 'Java', minRating: 6, importance: 'medium' },
      { name: 'SQL', minRating: 6, importance: 'medium' },
    ],
    optionalSkillSpecs: [
      { name: 'Documentation', minRating: 6 },
      { name: 'Spring Boot', minRating: 5 },
    ],
    location: 'Ottawa',
    remote: true,
    teamSize: 2,
    seniority: 'Senior',
    staffingMode: 'Team',
    status: 'At Risk',
  },
  {
    id: 'T008',
    name: 'AI Governance Launch Kit',
    type: 'Internal Work',
    description: 'Create a starter governance package for model intake, risk review, compliance sign-off, and manager training.',
    urgency: 'Medium',
    deadline: '2026-07-08',
    estHours: 70,
    requiredSkills: ['AI Governance', 'Model Risk', 'Compliance', 'Stakeholder Management'],
    optionalSkills: ['Training', 'Risk Assessment'],
    requiredSkillSpecs: [
      { name: 'AI Governance', minRating: 7, importance: 'critical' },
      { name: 'Model Risk', minRating: 6, importance: 'high' },
      { name: 'Compliance', minRating: 6, importance: 'medium' },
      { name: 'Stakeholder Management', minRating: 6, importance: 'medium' },
    ],
    optionalSkillSpecs: [
      { name: 'Training', minRating: 5 },
      { name: 'Risk Assessment', minRating: 5 },
    ],
    location: 'Remote',
    remote: true,
    teamSize: 1,
    seniority: 'Mid-Senior',
    staffingMode: 'One Employee',
    status: 'Needs Review',
  },
];
